[[redirects]]
  from = "http://maktabavto.uz/*"
  to = "https://www.maktabavto.uz/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://maktabavto.uz/*"
  to = "https://www.maktabavto/:splat"
  status = 301
  force = true
